version: "3.7"
services:
  euruka:
    image: ansv-registry-servive
    hostname: ansv-registry-service
    build: ./euruka
    ports:
      - "8052:8052"
    healthcheck:
      test: curl --fail http://host.docker.internal:8052 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - microservices
#  gateway:
#    image: ansv-gateway
#    hostname: ansv-gateway
#    build: ./gateway
#    ports:
#      - "8055:8055"
#    healthcheck:
#      test: curl --fail http://host.docker.internal:8055 || exit 1
#      interval: 60s
#      retries: 5
#      start_period: 20s
#      timeout: 10s
#    networks:
#      - microservices
#    depends_on:
#      - euruka
#  authorization:
#    image: ansv-authorization
#    hostname: ansv-authorization
#    build: ./authorization-server
#    ports:
#      - "8053:8053"
#    healthcheck:
#      test: curl --fail http://host.docker.internal:8053 || exit 1
#      interval: 60s
#      retries: 5
#      start_period: 20s
#      timeout: 10s
#    environment:
#      - spring_rabbitmq_host=host.docker.internal
#      - spring_rabbitmq_port=5672
#      - spring_rabbitmq_username=guest
#      - spring_rabbitmq_password=guest
#      - spring_rabbitmq_virtualHost=/
#      - spring_rabbitmq_exchange=task-management.req.events
#      - spring_rabbitmq_routingkey=detail.user.req
#      - spring_rabbitmq_queue=detail.user.task-management.req.queue
#      - spring_rabbitmq_exchange-received=user-received.exchange
#      - spring_rabbitmq_routingkey-received=user-received.routingkey
#      - spring_rabbitmq_queue-received=user-received.queue
#    depends_on:
#      - gateway
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - microservices
networks:
  microservices:
    name: microservices
