version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    ports:
      - 5673:5673
      - 5672:5672
      - 15672:15672
    networks:
      - microservices
    depends_on:
      - euruka
  euruka:
    image: ansv-registry
    hostname: ansv-registry
    build: ./euruka
    ports:
      - "8052:8052"
    networks:
      - microservices
  gateway:
    image: ansv-gateway
    hostname: ansv-gateway
    build: ./gateway
    ports:
      - "8055:8055"
    networks:
      - microservices
    depends_on:
      - rabbitmq
  authorization:
    image: ansv-authorization
    hostname: ansv-authorization
    build: ./authorization-server
    ports:
      - "8053:8053"
    environment:
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_port=5672
      - spring_rabbitmq_username=guest
      - spring_rabbitmq_password=guest
      - spring_rabbitmq_virtualHost=/
      - spring_rabbitmq_exchange=task-management.req.events
      - spring_rabbitmq_routingkey=detail.user.req
      - spring_rabbitmq_queue=detail.user.task-management.req.queue
    depends_on:
      - gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - microservices
networks:
  microservices:
    name: microservices
