version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    ports:
      - 5673:5673
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: curl --fail http://localhost:15672 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - microservices
    depends_on:
      - "gateway"
  euruka:
    image: ansv-registry-servive
    hostname: ansv-registry-service
    build: ./euruka
    ports:
      - "8052:8052"
    healthcheck:
      test: curl --fail http://localhost:9052 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - microservices
  gateway:
    image: ansv-gateway
    hostname: ansv-gateway
    build: ./gateway
    ports:
      - "8055:8055"
    healthcheck:
      test: curl --fail http://localhost:9055 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - microservices
    depends_on:
      - "euruka"
  authorization:
    image: ansv-authorization
    hostname: ansv-authorization
    build: ./authorization-server
    ports:
      - "8053:8053"
    healthcheck:
      test: curl --fail http://localhost:9053 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_port=5672
      - spring_rabbitmq_username=guest
      - spring_rabbitmq_password=guest
      - spring_rabbitmq_virtualHost=/
      - spring_rabbitmq_exchange=task-management.req.events
      - spring_rabbitmq_routingkey=detail.user.req
      - spring_rabbitmq_queue=detail.user.task-management.req.queue
    depends_on:
      - "rabbitmq"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - microservices
networks:
  microservices:
    name: microservices
    driver: brigde
