version: "3.7"
services:
  euruka:
    image: ansv-registry-servive
    hostname: ansv-registry-service
    build: ./euruka
    ports:
      - "8052:8052"
    healthcheck:
      test: curl --fail http://host.docker.internal:8052 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - microservices
  gateway:
    image: ansv-gateway
    hostname: ansv-gateway
    build: ./gateway
    ports:
      - "8055:8055"
    healthcheck:
      test: curl --fail http://host.docker.internal:8055 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - microservices
    depends_on:
      - euruka

networks:
  microservices:
    name: microservices
