
server:
    port: 8053

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8052/eureka/ 
  instance:
    hostname: localhost

spring:
  application:
    name: authorization
  ldap:
    server:
      base: CN=Users,DC=ansv,DC=vn
    authen:
      url: ldap://172.24.104.6:389
      managerDn: CN=Admin,CN=Users,DC=ansv,DC=vn
      managerPassword: 123456
      filter: userPrincipalName
  main:
    banner-mode: off

#jwttoken
app:
    jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
    tokenValidity: 604800000

# spring.ldap 
# spring:
#   ldap:
#     base-dn: CN=Users,DC=ansv,DC=vn
#     port: 389
#     credential:
#        username: CN=Admin,CN=Users,DC=ansv,DC=vn
#        password: 123456



    
      


# spring.ldap.authen.url=ldap://172.24.104.6:389
# spring.ldap.authen.port=389
# spring.ldap.server.base=CN=Users,DC=ansv,DC=vn
# spring.ldap.authen.managerDn=CN=Admin,CN=Users,DC=ansv,DC=vn
# spring.ldap.authen.managerPassword=123456
# spring.ldap.authen.dn-patterns=CN=Users,DC=ansv,DC=vn
# spring.ldap.authen.filter=userPrincipalName


# logging.level.root = debug
# logging.level.org.springframework = debug

