
server:
    port: 8053

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8052/eureka/ 
  instance:
    hostname: localhost

spring:
  application:
    name: authentication
  ldap:
    server:
      base: CN=Users,DC=ansv,DC=vn
    authen:
      url: ldap://172.24.104.6:389
      managerDn: CN=Admin,CN=Users,DC=ansv,DC=vn
      managerPassword: 123456
      filter: userPrincipalName
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/Authorization
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false

logging:
  level:
    root: debug
  org:
    springframework: debug
  hibernate:
      SQL: true


#jwttoken
app:
    jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
    tokenValidity: 604800000




    

