server:
  port: 8052
  address: 172.19.0.2

spring:
  application:
    name: ansv-registry


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #      defaultZone: http://ansv-registry:8052/eureka
      #      defaultZone: http://localhost:8052/eureka
      defaultZone: http://172.19.0.2:8052/eureka